// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzxoKtEeGdnhQQ6g6b1BjDQSVj4ivGt_w',
    appId: '1:274292413711:web:c2f848d57ca24fb0845a7a',
    messagingSenderId: '274292413711',
    projectId: 'rdvote-22284',
    authDomain: 'rdvote-22284.firebaseapp.com',
    databaseURL: 'https://rdvote-22284-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rdvote-22284.appspot.com',
    measurementId: 'G-GYMR11FD7C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6zVwnCuP8zL5e-Rx7bTG8Ip0V3G5cHu4',
    appId: '1:274292413711:android:0cad1f21d130eaf1845a7a',
    messagingSenderId: '274292413711',
    projectId: 'rdvote-22284',
    databaseURL: 'https://rdvote-22284-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rdvote-22284.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6dKbgrsP7P8ZF4Hb_xWR9FKsoq_TL5-Y',
    appId: '1:274292413711:ios:f1b25436ee4e3258845a7a',
    messagingSenderId: '274292413711',
    projectId: 'rdvote-22284',
    databaseURL: 'https://rdvote-22284-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rdvote-22284.appspot.com',
    androidClientId: '274292413711-43k8j5noeqho7c9fr00914e4ik4od6bv.apps.googleusercontent.com',
    iosClientId: '274292413711-sp142vbjlst4v0eu6jklskhmm6frm548.apps.googleusercontent.com',
    iosBundleId: 'com.seielika.rdVote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6dKbgrsP7P8ZF4Hb_xWR9FKsoq_TL5-Y',
    appId: '1:274292413711:ios:f1b25436ee4e3258845a7a',
    messagingSenderId: '274292413711',
    projectId: 'rdvote-22284',
    databaseURL: 'https://rdvote-22284-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rdvote-22284.appspot.com',
    androidClientId: '274292413711-43k8j5noeqho7c9fr00914e4ik4od6bv.apps.googleusercontent.com',
    iosClientId: '274292413711-sp142vbjlst4v0eu6jklskhmm6frm548.apps.googleusercontent.com',
    iosBundleId: 'com.seielika.rdVote',
  );
}
